-- FULL Orchid Species Insert

INSERT INTO genus (genus_name) VALUES
('Acanthophippium'),
('Acriopsis'),
('Agrostophyllum'),
('Anoectochilus'),
('Appendicula'),
('Blepharoglossum'),
('Brachypeza'),
('Bryobium'),
('Bulbophyllum'),
('Calanthe'),
('Cephalantheropsis'),
('Cheirostylis'),
('Coelogyne'),
('Corymborkis'),
('Cryptostylis'),
('Cylindrolobus'),
('Cymboglossum'),
('Cystorchis'),
('Dendrobium'),
('Dendrochilum'),
('Dienia'),
('Epiblastus'),
('Epipogium'),
('Erythrodes'),
('Grammatophyllum'),
('Lepidogyne'),
('Mycaranthes'),
('Oberonia'),
('Octarrhena'),
('Odontochilus'),
('Oxystophyllum'),
('Paraphaius'),
('Peristylus'),
('Phaius'),
('Phalaenopsis'),
('Pholidota'),
('Phreatia'),
('Pinalia'),
('Podochilus'),
('Pteroceras'),
('Renanthera'),
('Rhomboda'),
('Robiquetia'),
('Spathoglottis'),
('Stichorkis'),
('Taeniophyllum'),
('Thelasis'),
('Thrixspermum'),
('Trichotosia'),
('Vanda'),
('Vrydagzynea');

INSERT INTO species (genus_id, scientific_name)
VALUES
(1, 'Acanthophippium mantinianum'),
(2, 'Acriopsis liliifolia var. lilifolia'),
(3, 'Agrostophyllum elongatum'),
(3, 'Agrostophyllum loheri'),
(4, 'Anoectochilus sp.'),
(5, 'Appendicula crotalina'),
(5, 'Appendicula elmeri'),
(5, 'Appendicula leytensis'),
(5, 'Appendicula malindangensis'),
(5, 'Appendicula cf. pendula'),
(5, 'Appendicula undulata var. longicalcarata'),
(5, 'Appendicula weberi'),
(5, 'Appendicula sp. 1'),
(5, 'Appendicula sp. 2'),
(5, 'Appendicula sp. 3'),
(5, 'Appendicula sp. 4'),
(5, 'Appendicula sp. 5'),
(6, 'Blepharoglossum condylobulbon'),
(6, 'Blepharoglossum grossum'),
(7, 'Brachypeza unguiculata'),
(8, 'Bryobium senile'),
(9, 'Bulbophyllum antenniferum'),
(9, 'Bulbophyllum colubrimodum'),
(9, 'Bulbophyllum mucronatum subsp. alagense'),
(9, 'Bulbophyllum odoratum'),
(9, 'Bulbophyllum sp. 1'),
(9, 'Bulbophyllum sp. 2'),
(9, 'Bulbophyllum sp. 3'),
(10, 'Calanthe davaensis'),
(10, 'Calanthe cf. furcata'),
(10, 'Calanthe sp.'),
(11, 'Cephalantheropsis aff. halconensis'),
(12, 'Cheirostylis octodactyla'),
(13, 'Coelogyne rochussenii'),
(13, 'Coelogyne sp.'),
(14, 'Corymborkis veratrifolia'),
(15, 'Cryptostylis acutata'),
(15, 'Cryptostylis taiwaniana'),
(16, 'Cylindrolobus longissimus'),
(17, 'Cymboglossum cymbidiifolium'),
(18, 'Cystorchis sp.'),
(19, 'Dendrobium boosii'),
(19, 'Dendrobium cf. chloranthum'),
(19, 'Dendrobium orbilobulatum'),
(19, 'Dendrobium planum'),
(19, 'Dendrobium plicatile'),
(19, 'Dendrobium pterocarpum'),
(19, 'Dendrobium rhombeum'),
(19, 'Dendrobium setigerum'),
(19, 'Dendrobium tiongii'),
(19, 'Dendrobium uniflorum'),
(20, 'Dendrochilum coccineum'),
(20, 'Dendrochilum aff. elmeri'),
(20, 'Dendrochilum glumaceum'),
(20, 'Dendrochilum migueldavidii'),
(20, 'Dendrochilum sp. 1'),
(20, 'Dendrochilum sp. 2'),
(21, 'Dienia carinata'),
(22, 'Epiblastus merrillii'),
(23, 'Epipogium roseum'),
(24, 'Erythrodes latifolia'),
(25, 'Grammatophyllum wallisii'),
(26, 'Lepidogyne longifolia'),
(27, 'Mycaranthes candoonensis'),
(27, 'Mycaranthes mindanaensis'),
(28, 'Oberonia serrulata'),
(29, 'Octarrhena elmeri'),
(30, 'Odontochilus marivelensis'),
(30, 'Odontochilus yakushimensis'),
(31, 'Oxystophyllum elmeri'),
(32, 'Paraphaius flavus'),
(33, 'Peristylus goodyeroides'),
(34, 'Phaius tankervilleae'),
(35, 'Phalaenopsis mariae'),
(35, 'Phalaenopsis reichenbachiana'),
(35, 'Phalaenopsis sanderiana'),
(36, 'Pholidota imbricata'),
(37, 'Phreatia amesii'),
(37, 'Phreatia sulcata'),
(37, 'Phreatia sp. 1'),
(37, 'Phreatia sp. 2'),
(38, 'Pinalia floribunda'),
(38, 'Pinalia nielsenii'),
(39, 'Podochilus lucescens'),
(39, 'Podochilus plumosus'),
(39, 'Podochilus sp.'),
(40, 'Pteroceras longicalcareum'),
(41, 'Renanthera monachica'),
(42, 'Rhomboda lanceolata'),
(43, 'Robiquetia bifidus'),
(43, 'Robiquetia compressa'),
(44, 'Spathoglottis plicata'),
(45, 'Stichorkis cf. compressa'),
(45, 'Stichorkis gracilis'),
(45, 'Stichorkis leytensis'),
(45, 'Stichorkis philippinensis'),
(46, 'Taeniophyllum philippinense'),
(46, 'Taeniophyllum sp.'),
(47, 'Thelasis carinata'),
(48, 'Thrixspermum bellamabantae'),
(48, 'Thrixspermum elmeri'),
(48, 'Thrixspermum merguense'),
(48, 'Thrixspermum rostratum'),
(48, 'Thrixspermum sp.'),
(49, 'Trichotosia odorifera'),
(49, 'Trichotosia aff. ramosii'),
(50, 'Vanda cootesii'),
(51, 'Vrydagzynea sp.');
